calibration:
  cv_folds: 5
  method: isotonic
datasets:
  externals:
  - GSE199727
  - GSE180133
  train_source: GSE111727
evaluation:
  conformal_alpha: 0.1
  metrics:
  - auroc
  - auprc
  - ece
model:
  max_iter: 800
  random_state: 42
  type: logistic
paths:
  interim: data/interim
  logs: runs
  processed: data/processed
  raw: data/raw
prep:
  hvg_intersection_with_donor: true
  hvg_n: 3000
  log1p: true
  min_cells_per_gene: 3
  min_genes_per_cell: 100
  normalize: size_factor
